name: Prezi Workshop
favicon: null
layout_spectrum: 0.8352074830327183
typography_spectrum: 0.7975474186241627
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7979917868506163
  lightness: 0.8733924662228674
  saturation: 0.5421700209844857
  rhythmicContrast: 0.13382568978704512
purpose: []
